### ISSUE TITLE
VS 2012 Website

### ISSUE THREAD

**Issue by Jake-Barrow** [madskristensen/FileNesting#15]
Hi, we recently wanted to start using this plugin and it works well for some items, such as Web Applications and Windows Forms.

However when you create an Empty ASP.NET Website the plugin doesn't appear to load, we don't even get the option on the right-click menu of "File Nesting". This occurs if you load a new Website or open a pre-existing site.

Could you please take a look at this as we very much would like to use this for nesting .js files under our web forms in our Websites.

Thanks

**Comment by madskristensen** [comment]
Website projects in Visual Studio doesn't support dynamic file nesting. Web Essentials provide some static rules for file nesting, but since dynamic nesting isn't supported I didn't wanted to add that logic to this extension
