### ISSUE TITLE
Internal Error During Manual Nesting C++ Item

### ISSUE THREAD

**Issue by sergegers** [madskristensen/FileNesting#29]
Windows 7 x64
Visual Studio 2015 Preview
VC++ dll project.

File Nesting -> Nest Item -> stdafx.h -> Select Parent -> stdafx.cpp

---------------------------
Microsoft Visual Studio
---------------------------
An internal error occurred. Please contact Microsoft Product Support Services.
---------------------------
OK   
---------------------------

**Comment by madskristensen** [comment]
Fixed
