### ISSUE TITLE
Autonest .js and .js.map files into .ts (TypeScript) file.

### ISSUE THREAD

**Issue by NN---** [madskristensen/FileNesting#30]

**Comment by fmorriso** [comment]
I like the idea, but it should be configurable, so everyone can decide for themselves how "deep" the nesting should go.  For example, should abc.js, abc.min.js, abc.js.map, abs.min.js.map *ALL* be directly nested under abc.ts?  Or, should there be the option of nesting the .map file underneath the "parent" .js file?  One size does not fit all, so flexibility on this one is imperative.

**Comment by NN---** [comment]
I am pretty sure most of the people want everything to be nested under .ts file.
Configurable feature is nice if someone ever needs it.

**Comment by madskristensen** [comment]
This is already supported. What type of project are you not seeing this in? ASP.NET 5, WinForms, Cordova, or...?

**Comment by NN---** [comment]
I use ChromeExtnesion project template from SideWaffle (http://sidewaffle.com/)

I added a new typescript file.
Wrote some code
Added js and map files.

When I press AutoNest it doesn't nest them.

**Comment by fmorriso** [comment]
Mads:
You need to add the following to your example, perhaps using your "Bundler & Minifier" tool to fully appreciate the issue I'm trying to raise:

foo.min.js.map

Where should the above file go when AutoNest is turned on?  It seems to me there are two competing yet equally valid "preferences" that should be respected (and thus configurable):

1.  Put foo.min.js.map *UNDERNEATH* foo.js 
or
2. Put foo.min.js.map *UNDERNEATH* it's "parent" foo.min.js.

To the commenter that said "I'm pretty sure...." - that's the kind of presumptuous, "I know what is best, so shut up and obey" attitude that infuriates people like me.   What is wrong with having choices?  One size DOES NOT FIT ALL !!!

**Comment by madskristensen** [comment]
@NN did you enable all the nesting rules in the settings?

**Comment by NN---** [comment]
@madskristensen Didn't know the extension has so many rules.
It should be more obvious like an item in the context manu for additional rules which opens the settings window.
