### ISSUE TITLE
File Nesting with Folders

### ISSUE THREAD

**Issue by mojtabakaviani** [madskristensen/FileNesting#31]
every project have many scripts and styles files. some jquery files, some bootstrap files and other libraries that usually start with jquery. and bootstrap. or standard naming is a [library].[plugin].[js/css]
please add file nesting with folders that automatically create folder with library and show plugin.js in folder's. 
![nesting folders](https://cloud.githubusercontent.com/assets/1667525/5595524/86c4f912-928a-11e4-83e5-e80ac99b6a90.png)
I think it is good idea can add in new version of visual studio for easy manage many library scripts.

**Comment by madskristensen** [comment]
I don't think that's a good idea to bake into this extension.
