### ISSUE TITLE
Not working on Cordova JS Project

### ISSUE THREAD

**Issue by JCKodel** [madskristensen/FileNesting#32]
In a Tools for Apache Cordova project, nesting doesn't work:

---------------------------
Microsoft Visual Studio
---------------------------
Unable to add project item "scripts\angular.min.js": ADDRESULT_Cancel
---------------------------
OK   
---------------------------

While trying to nest angular.min.js into angular.js

**Comment by madskristensen** [comment]
The Apache Cordova project system in VS doesn't support file nesting. All I can do is to make the error go away, I can't make file nesting work

**Comment by JCKodel** [comment]
Sorry for that... 
I though would be possible because Web Essentials bundle works as intended:

   <Content Include="Content\css\css.css">
      <DependentUpon>css.css.bundle</DependentUpon>
    </Content>
    <Content Include="Content\css\css.css.bundle" />
    <Content Include="Content\css\css.min.css">
      <DependentUpon>css.css</DependentUpon>
    </Content>

**Comment by AGBrown** [comment]
@madskristensen I managed to get this to work. I have tested in:

 - VS 2013 Update 4 (Win 8.1) 
 - with Visual Studio Tools for Apache Cordova (v0.3.22015.1) 
 - using a Tools for Apache Cordova project
 - with both `.html`, `.js`, `.min.js` and `.min.js.map` files in the project (the html files behave slightly differently)

Pull request to follow.

**Comment by AGBrown** [comment]
@madskristensen. [Pull request created](https://github.com/madskristensen/FileNesting/pull/34). Incidentally this also seems to fix a related issue I was seeing where un-nesting in cordova projects put the un-nested item into the root of the project instead of the original folder.
