### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by ddechant** [madskristensen/FileNesting#35]
When creating an MVC project (Empty- > MVC) right when opening Visual Studio I get this error. The project does not get fully generated: 
![image](https://cloud.githubusercontent.com/assets/263218/7378413/6a71107c-edaa-11e4-97cc-92f3db5885c4.png)

When closing the partially created solution and creating a new one, the message is not displayed and the solution is created without issue:
![image](https://cloud.githubusercontent.com/assets/263218/7378477/cc1b5724-edaa-11e4-9894-0dcfab06a640.png)

The error returns when I restart Visual Studio (and try creating a new solution).
The problem goes away entirely once I disable the FileNesting extension (and restarting Visual Studio).

I've gone through my ActivityLog.xml and the only error I found was this:
```xml
  <entry>
    <record>1584</record>
    <time>2015/04/28 19:39:05.884</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.Windows.DevelopmentKit.Desktop&apos; is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.0\DESKTOP SDK\...</description>
    <path>C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\DESKTOP SDK\</path>
  </entry>
```
There is also a significant number of warnings. If needed I can share.

**Comment by madskristensen** [comment]
That is odd. I've never heard of this issue and I don't see any FileNesting specifics in the partial error log you attached. Is the issue fixed if you uninstall FileNesting? If so, can you please attach the whole ActivityLog.xml?

**Comment by ddechant** [comment]
Uninstalling FileNesting also fixes the issue. The log is attached here: https://dl.dropboxusercontent.com/u/2180093/ActivityLog.xml
