### ISSUE TITLE
Exceptions when nesting in VS 2015 RC

### ISSUE THREAD

**Issue by Ixonal** [madskristensen/FileNesting#36]
Only adding this because VS 2015 is listed as being supported (even if it's not officially released yet)

This is happening in an ASP.NET 5 website in Visual Studio 2015 RC. By default, Visual Studio is doing some nesting automatically with similarly named files, but I wanted some more control over what is nested within what, so I got this extension. Unfortunately, when I try to right click and nest a file somewhere else, I get the error "Unable to add project item "path/to/file": ADDRESULT_Cancel", and when I try to un-nest a file, I get the error "Exception has been thrown by the target of an invocation". I've tried uninstalling and reinstalling with the same results. Any idea what's going on there?

**Comment by madskristensen** [comment]
This extension cannot work on asp.net 5 projects. I'll fix it so it doesn't error at least

**Comment by Ixonal** [comment]
Huh, why can't it work in that type of project, in particular?

**Comment by madskristensen** [comment]
Because there is no .csproj file to store the file dependencies in

**Comment by Ixonal** [comment]
ohhh, I see, the xproj file must have a different schema then?

**Comment by madskristensen** [comment]
.xproj doesn't contain a list of files and their dependencies. Still MSBuild format, but very different

**Comment by Ixonal** [comment]
I'm guessing it's just looking at the files in the directory and sub-directories instead for what files are there. Makes sense, considering it automatically includes files created in my build process and nests them in the solution explorer. 

Are xproj files going to be used for more types of projects in the future, or is this a one-off thing specific to asp.net 5 projects?

**Comment by Ixonal** [comment]
Since the file dependencies can't be specified explicitly, could there be an option to specify patterns of what is nested below what? It'd still be automatic in these cases, but the automatic nesting would be according to the dev's wishes. Just a thought.

**Comment by madskristensen** [comment]
Yes, the ASP.NET 5 project system has support for automatic nesting through a VS extension. A lot of the rules are already built in to the project system for nesting, but more could be added in a separate extension.
