### ISSUE TITLE
Choosing "auto-nest selected items" does nothing in VS2015

### ISSUE THREAD

**Issue by chrismbarr** [madskristensen/FileNesting#41]
This worked fine for me in VS2013, but since updating to 2015, this no longer works.  I can manually nest each file & choose it's parent from a list, but this become a hassle very quickly.

I am using version 2.2.26 of this extension.

**Comment by floatas** [comment]
I haven't used FileNesting with VS2013, but on VS2015 I had to set "Enable extension rule" and "Enable known file type rule" to true, then auto nesting started to work. Have you checked your settings ?

**Comment by chrismbarr** [comment]
Ah excellent, yes that fixes it!  For some reason my default preferences got reset when I installed this in VS2015.
