### ISSUE TITLE
Add to Tools for Apache Cordova with typescript

### ISSUE THREAD

**Issue by jimior2** [madskristensen/FileNesting#42]
I'm testing on the Web Project and Cordova project in VS2015. And auto nesting files could work on typescript of web project but not on Cordova project,

**Comment by madskristensen** [comment]
Cordova as well as ASP.NET 5 doesn't support custom file nesting, unfortunately. There is nothing this extension can do to fix that

**Comment by jimior2** [comment]
Got it, thanks.

**Comment by shyamal890** [comment]
@madskristensen Are VS guys working on this? It is a necessity when your application size increases.

**Comment by madskristensen** [comment]
@shyamal890 Let's ask @jmatthiesen
