### ISSUE TITLE
Extension disabled

### ISSUE THREAD

**Issue by ernstc** [madskristensen/FileNesting#46]
Every time I enable this extension after a while I find it disabled. If I enable it again than I can use it, but at the next startup of Visual Studio the extesion is again disabled.

**Comment by madskristensen** [comment]
Sounds like you need to clear the MEF cache. It has nothing to do with this extension, but is a general problem with VS2015. See this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by ernstc** [comment]
I have this issue only with these extesions:
* Bundle & Minifier
* File Nesting
* Image Optimizer
* Web Analyzer
* Web Compiler
* Web Essentials 2015.1

I have tried to re-enabled all these extensions, restarted VS2015, cleared
MEF cache, restarted VS2015 and then all these extensions were again
disabled.


2016-01-15 17:34 GMT+01:00 Mads Kristensen <notifications@github.com>:

**Comment by madskristensen** [comment]
The VS team is looking into fixing this issue. There is nothing about any of these extensions that causes that behavior
