### ISSUE TITLE
Feature: enable drag&drop gesture

### ISSUE THREAD

**Issue by kzu** [madskristensen/FileNesting#49]
Not sure if this is even possible, but it would be awesome if just dragging a file onto another in the solution explorer caused them to nest. No more need for menus I guess ;).

Currently, when you do that in VS, you get a useless "Cannot move [file]. The destination folder is the same as the source folder.". Would be awesome if that could be overriden for file-over-file dragging.

**Comment by IanYates** [comment]
Similar to #27

**Comment by kzu** [comment]
Closing as dupe of #27
