### ISSUE TITLE
Could not load file or assembly 'FileNesting, Culture=neutral' or one of its dependencies...

### ISSUE THREAD

**Issue by JRi90** [madskristensen/FileNesting#52]
### Installed product versions
- Visual Studio: Community 2015
- This extension: 2.3.46

### Description
I get the following error, if I try "Nest Item...":
![filenesting](https://cloud.githubusercontent.com/assets/18489446/14571703/f75f869c-034a-11e6-8ce0-1f0816262cbc.png)

### Steps to recreate
1. Right-click on Item
2. File Nesting
3. Nest Item...

**Comment by madskristensen** [comment]
Thanks, if you update the extension to the newly released 2.3.49 then it should be fixed.

**Comment by JRi90** [comment]
Thanks, works with 2.3.54.
(Not tested with 2.3.49)
