### ISSUE TITLE
Throw a Error when VS start, about VsixLogger.

### ISSUE THREAD

**Issue by chsword** [madskristensen/FileNesting#53]
### Installed product versions
- Visual Studio: 2015 update2
- This extension: 2.3.49

### Description
Throw a Error when vs start.

> Could not load file or assembly “VsixLogger, Version=1.0.15.0, Culture=en-US, PublicKeyToken=null” or one of its dependencies.

```
<entry>
    <record>546</record>
    <time>2016/04/16 02:45:55.222</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VSPackage][&#x672A;&#x80FD;&#x52A0;&#x8F7D;&#x6587;&#x4EF6;&#x6216;&#x7A0B;&#x5E8F;&#x96C6;&#x201C;VsixLogger, Version=1.0.15.0, Culture=en-US, PublicKeyToken=null&#x201D;&#x6216;&#x5B83;&#x7684;&#x67D0;&#x4E00;&#x4E2A;&#x4F9D;&#x8D56;&#x9879;&#x3002;&#x7CFB;&#x7EDF;&#x627E;&#x4E0D;&#x5230;&#x6307;&#x5B9A;&#x7684;&#x6587;&#x4EF6;&#x3002;]:{   &#x5728; MadsKristensen.FileNesting.VSPackage.Initialize()&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)}</description>
    <guid>{6C799BC4-0D4C-4172-98BC-5D464B612DCA}</guid>
    <hr>80070002</hr>
    <errorinfo>未能加载文件或程序集“VsixLogger, Version=1.0.15.0, Culture=en-US, PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件。</errorinfo>
  </entry>
  <entry>
    <record>547</record>
    <time>2016/04/16 02:45:55.223</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [VSPackage]</description>
    <guid>{6C799BC4-0D4C-4172-98BC-5D464B612DCA}</guid>
    <hr>80070002</hr>
    <errorinfo>未能加载文件或程序集“VsixLogger, Version=1.0.15.0, Culture=en-US, PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件。</errorinfo>
  </entry>
```

In the folder "\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\laxwgtzb.bak" :
![image](https://cloud.githubusercontent.com/assets/274085/14578688/42d61c14-03c1-11e6-86c8-ccd2e2b88707.png)

**Comment by IanYates** [comment]
I have the same issue.  My system change between yesterday and today is that I upgraded from the early-access R# to the just-released R#.

VS still loads normally, except I can't use the File Nesting menu as I get the error message again.

Relevant bit of the activity log for me...

1547 ERROR SetSite failed for package [VSPackage][Could not load file or assembly 'VsixLogger, Version=1.0.15.0, Culture=en-US, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.]:{ at MadsKristensen.FileNesting.VSPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)} {6C799BC4-0D4C-4172-98BC-5D464B612DCA} 80070002 VisualStudio 2016/04/16 02:53:08.633 
1548 ERROR End package load [VSPackage] {6C799BC4-0D4C-4172-98BC-5D464B612DCA} 80070002 VisualStudio 2016/04/16 02:53:08.633

**Comment by madskristensen** [comment]
Thanks for sending this bug report. I cannot repro this myself, so can I ask you to try the new [CI build version 2.3.52](http://vsixgallery.com/extension/6c799bc4-0d4c-4172-98bc-5d464b612dca/) or later, please?

**Comment by chsword** [comment]
version 2.3.52 works well

**Comment by IanYates** [comment]
Seems to work well for me too.  Thanks!
