### ISSUE TITLE
File Nesting doesn't work in ASP.NET Core projects on Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by kollster** [madskristensen/FileNesting#54]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 2
- This extension: 2.3.54

### Description
File Nesting doesn't work at all in ASP.NET Core projects on Visual Studio 2015 Update 2.

### Steps to recreate
1. Create or open an ASP.NET Core project in Visual Studio 2015 Update 2.
2. Create two files e.g. FileParent.txt and FileChild.txt.
3. Select FileChild.txt in Solution Explorer and press Ctrl + Alt + N for File Nesting.
4. In the popup, select FileParent.txt as parent.
5. Notice that FileChild.txt does not get nested under FileParent.txt.

### Expected behavior
It is expected that FileChild.txt should get nested under FileParent.txt.

**Comment by madskristensen** [comment]
The ASP.NET Core project type doesn't support file nesting beyond its own built in rules for nesting. This extension can do nothing to remedy that, unfortunately. I know the VS web tooling team is looking at making the nesting rules configurable.
