### ISSUE TITLE
File Nesting doesn't work in NodeTools projects on Visual Studio 2015

### ISSUE THREAD

**Issue by RefactorMan** [madskristensen/FileNesting#55]
### Installed product versions
- Visual Studio:  2015 Community
- File Nesting v2.3.54

### Description
File Nesting doesn't work in Node Tools projects on Visual Studio 2015.
project file extention ".njsproj"

### Current behavior
I can't see the "File Nesting" option when right-click on files/project in Solution Explorer.
In addition, I tried to enable Auto Nesting via Tools -> Options -> File Nesting and  its doesn't work.

**Comment by madskristensen** [comment]
The project system provided by NTVS doesn't support file nesting. The issue should be fixed by NTVS before support can be added by this extension

**Comment by falahati** [comment]
@madskristensen this is not the case with VS2019 tho. In fact, I am able to nest files by modifying the project file manually. And sometimes your 'Compiler' extension does it too with `.less` and `.js` files that I have in my project. But usually, it doesn't. Is there something else that I am missing and should be fixed before we can use this extension?

The File Nesting extension as of now doesn't work in `.njsproj` files. The menu is there but clicking on 'Nest items...' throws an "Object reference not set to an instance of an object" error.
