### ISSUE TITLE
Possible to support VS 2017 RC?

### ISSUE THREAD

**Issue by IanYates** [madskristensen/FileNesting#64]
### Installed product versions
- Visual Studio: 2017 Enterprise RC
- This extension: N/A

### Description
I was able to install this extension in the last preview of VS'15 before it was renamed to VS 2017.  I guess the extension gallery is a bit more filtered in the "go live" VS 2017 that's just come out because I can't find this extension to install.

### Steps to recreate
Search for this extension in VS 2017

### Current behavior
Extension not available for installation.

### Expected behavior
Extension is available

Really appreciate this extension.  It, and the quick-add-file extension, are the only things I'm missing from a complete VS experience.  Thanks! :)

**Comment by IanYates** [comment]
Actually, I just found the version from the gallery, when manually downloaded, now lets me install into VS 2017.

**Comment by madskristensen** [comment]
Fixed
