### ISSUE TITLE
Plugin broken in Visual Studio 2017 RC

### ISSUE THREAD

**Issue by ciel** [madskristensen/FileNesting#65]
### Installed product versions
- Microsoft Visual Studio Professional 2017 RC, Version 15.0.25920.0 D15REL
- File Nesting, Version 2.5.65, Last updated 11/25/2016

### Description
All behavior fails to function.

### Steps to recreate
1. Create a new Console App (.NET Core), Class Library (.NET Standard), or ASP.NET Core Web Application (.NET Core) with `net45`, `net451, `net452`, `net46`, `net461`, `netstandard1.5`, or `netcoreapp1.0` for the target framework.
2. Create a sample file (eg. `file1.cs`)
3. Create a new file that would logically nest beneath the previous (eg, `file1.file2.cs`)
4. Right click the new file (`file1.file2.cs`) and select  `File Nesting` -> `Nest Item`.
5. Select `file1.cs` in the `Select parent` dialog.

None of the other functionality behaves, either.

### Current behavior
Files are not nested.

### Expected behavior
Files should be nested.

**Comment by ciel** [comment]
Not sure if this is valid or not, since I just saw on the README that there are known issues with .NET Core. However, the File Nesting plugin was working fine for me in the same project back on Visual Studio 2015.

**Comment by gregoryagu** [comment]
I have the same issue with typescript file nesting.

In VS15, test.ts would have test.js nested under it, and test.js.map nested under that.

This is no longer working in VS17RC.

**Comment by madskristensen** [comment]
.NET  Core apps don't yet support file nesting properly in VS2017 RC. It is coming for RTM though, so hang in there. 

I've updated this extension so it will support manual nesting of files in .NET Core

**Comment by ciel** [comment]
Hey, manual nesting is good enough for me for now! Thank you so much!

**Comment by ciel** [comment]
Is this change active in the build from the CI Build or the Visual Studio Marketplace?

**Comment by madskristensen** [comment]
@ciel It's released to the Marketplace

**Comment by ciel** [comment]
Unfortunately, that one does not even allow manual nesting in .net core in
VS2017 RC. It doesn't work for anything, not even non-core projects.

**Comment by madskristensen** [comment]
Fixed in the latest version I just released to the Marketplace

**Comment by ciel** [comment]
Hrnm... Unfortunately, even that one doesn't seem to work. Do I need to do
something special to get it to function, beyond just assigning manual
nesting?

**Comment by ciel** [comment]
Oh I see. It only works for a select few kinds of files. It doesn't work on
C# files.

**Comment by ciel** [comment]
Is it possible to make it work with C# files? Or is that a significant amount of plumbing? 

Either way, thank you so much for all the work you've done. I have like 8 of your extensions installed... not sure I could live without some of them!

**Comment by madskristensen** [comment]
@ciel Unfortunately not until the project system support is there. Hopefully by RTM

**Comment by ciel** [comment]
I understand. Thank you for the responses. I'll keep hoping they elect to do this! It was very helpful.

**Comment by ciel** [comment]
Do you have any idea if this is resolved in the new RC that came out yesterday?

**Comment by gregoryagu** [comment]
@ciel I upgraded to the latest version, and I still cannot nest *.cs files in an aspnetcore project.  However, I can nest *.ts files in an aspnetcore project just fine.  For me, that is all I need.

**Comment by madskristensen** [comment]
@ciel No, it hasn't been coded yet by the team. Hopefully it will be in by RTM

**Comment by ciel** [comment]
Just here with an update - I installed the newest RC of Visual Studio 2017, and automatic nesting does not work - but manual nesting does.
