### ISSUE TITLE
.NET Standard (Core) projects not working!

### ISSUE THREAD

**Issue by fahadabdulaziz** [madskristensen/FileNesting#82]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 2.6.67

### Description
Nesting in VS 2017 is not working. I saw in readme file that it is not support. but it really supported!

On any csproj that targets Microsoft.NET.Sdk, edit it to add :
```xml
  <ItemGroup>
    <Compile Update="ParentFile.*.cs">
      <DependentUpon>ParentFile.Generated.cs</DependentUpon>
    </Compile>
  </ItemGroup>
```

I'm not sure but I think it also supported in projects that targets Microsoft.NET.Sdk.Web

### Steps to recreate
1. Select two files
2. Right click
3. File Nesting -> Auto-nest selected files!

### Current behavior
Do nothing!

### Expected behavior
Do nesting and edit the CSProj to be like this:
```xml
  <ItemGroup>
    <Compile Update="ParentFile.*.cs">
      <DependentUpon>ParentFile.Generated.cs</DependentUpon>
    </Compile>
  </ItemGroup>
```

**Comment by kdawg1406** [comment]
Same here.

**Comment by RealDotNetDave** [comment]
Me too!
